# Generated by Django 5.1.4 on 2024-12-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('overlay_image', models.ImageField(blank=True, null=True, upload_to='overlays/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
